export const data_set = [
    {   
        "id":"1",
        "name":"俠盜獵車手", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"", 
        "count":4
    },
    {   
        "id":"2",
        "name":"宇宙機器人", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
       "purchase_price":1500,
        "selling_price":1790,  
        "img_path":"/Game/astro-bot-logo.png", 
        "count":4
    },
    {
        "id":"3",
        "name":"刺客教條：暗影者" , 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790,  
        "img_path":"/Game/Assassin's_Creed_Shadows_Logo.png", 
        "count":10
    },
    {   
        "id":"4",
        "name":"蜘蛛人2",
        "platformer":"PS5",
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/spider-man-2.png", 
        "count":6
    },
    {   
        "id":"5",
        "name":"羊蹄戰鬼", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790,  
        "img_path":"/Game/ghost-of-yotei-logo.png", 
        "count":4
    },
    {   
        "id":"6",
        "name":"要塞英雄", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/Fortnite.jpeg", 
        "count":3
    },
    {   
        "id":"7",
        "name":"nBA 2K25", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/n25-BAse-StAnDARD_EDitiOn_AnnOunCE-nA-StAtiC-ESRB-AGn.jpg", 
        "count":4
    },
    {
        "id":"8",
        "name":"艾爾登法環", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/img_dl.png", 
        "count":2
    },
    {   
        "id":"9",
        "name":"魔物獵人 荒野", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/monster_hunter.png", 
        "count":1
    }, 
    {   
        "id":"10",
        "name":"俠盜獵車手 VI", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/Grand_theft_Auto_VI_logo.png", 
        "count":4
    },
    {   
        "id":"11",
        "name":"俠盜獵車手 V", 
        "platformer":"PS5", 
        "production_used":"二手",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/Grand_theft_Auto_VI_logo.png", 
        "count":4
    },
    {   
        "id":"12",
        "name":"俠盜獵車手 III", 
        "platformer":"PS5", 
        "production_used":"新品",
        "type":"遊戲", 
        "purchase_price":1500,
        "selling_price":1790, 
        "img_path":"/Game/Grand_theft_Auto_VI_logo.png", 
        "count":4
    }
]