# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

RUN apt-get update
RUN apt-get install libpq-dev -y
RUN apt-get install postgresql-server-dev-all -y 
RUN apt-get -y install libpq-dev gcc
RUN export PATH=$PATH:/usr/lib/postgresql/13/bin/

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY . /app

# Expose the port your FastAPI application listens on
EXPOSE 8000

# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]