# # Stage-A
# # 用一個有 node 環境的 Image，來
# FROM node:lts-alpine

# # 建置 dist/
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . .
# RUN npm run build


# # Stage-B: 
# # 使用 NGINX image
# FROM nginx

# # 從 Stage-A COPY 過的內容，只取需要的 dist/ 資料夾，放入 NGINX Image 中
# WORKDIR /app
# COPY --from=0 /app/dist ./dist/
# # 當然別忘了我們的 NGINX 設定檔
# COPY conf.d/* /etc/nginx/conf.d/

#使用官方 Nginx 镜像
FROM nginx:latest 

# 將 Vue 應用程式的 dist 資料夾複製到容器內
COPY dist /usr/share/nginx/html 
# 將 Nginx 設定檔複製到容器內
COPY nginx.conf /etc/nginx/nginx.conf 
#  暴露 80 埠
EXPOSE 80 
# 啟動 Nginx
CMD ["nginx", "-g", "daemon off;"]